language: node_js
node_js:
  - "8"
  - "10"

sudo: required

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

script:
  - yarn test
